### ISSUE TITLE
NotImplementedError: Sorry, 'Feather STM32F405 Express with STM32F405RG' is not supported currently

### ISSUE THREAD

**Issue by dglaude** [pimoroni/physical_feather_pins#2]
```
File "pimoroni_physical_feather_pins/__init__.py", line 54, in <module>
NotImplementedError: Sorry, 'Feather STM32F405 Express with STM32F405RG' is not supported currently
```

I might work on fixing this right now... but this library is really "unusual" for somebody doing Circuit Python.

**Comment by Gadgetoid** [comment]
Thank you for looking into this. We deliberately kept the number of first-party supported Feather boards to a minimum to make sure we used ones that supported the Enviro+ well, and to avoid being caught in development hell. I'm all for expanding support! (Though the Feather ecosystem is positively dizzying at this point)

**Comment by dglaude** [comment]
@Gadgetoid you merged, so let's close this.
